### ISSUE TITLE
test graphelion.

### ISSUE THREAD

**Issue by wildone** [innovolve-ai/typerefinery#2]
test graphelion application.

identify good features in the UI, update the UI Features in the planning doc https://docs.google.com/presentation/d/1UIF6JzRFtxo00AQ-bdlBtMHEo9UE-RN_0jXJZZzwkmg/edit#slide=id.g10920fa4a6b_0_109.

**Comment by Rahul139-stack** [comment]
Here,we can switch the network view to gridview from dropdown near run icon at the button,
Copy nodes and insert to another view,zoom fit and autocomplete.Design your own styles for nodes and relations.
Use the default dashboard to interact with a graph store without writing Cypher
