### ISSUE TITLE
test neo4j.

### ISSUE THREAD

**Issue by wildone** [innovolve-ai/typerefinery#3]
test neo4j application.

identify good features in the UI, update the UI Features in the planning doc https://docs.google.com/presentation/d/1UIF6JzRFtxo00AQ-bdlBtMHEo9UE-RN_0jXJZZzwkmg/edit#slide=id.g10920fa4a6b_0_109.

**Comment by Rahul139-stack** [comment]
Neo4j UI features:

-In the sidebar, there are number of icons for various task.

-One icon for data connection, where are many attribute features -Node labels,relationship types and many more attributes and 80% of the screen is for query and connectivity where we can run the query and get results.

-In favorite bar , there many attributes like  local scripts to add empty favorite, on adding , there to  two window for running and connect to Neo4j which are collapsible ,expandable ,pin at top, close , fullscreen feature.

-Browser settings, where graph visualisation settings available, user interface,results frame.

-Using Built-In Guides.
-Change Graph Appearance
- Here we can have different types of views-graph,table,text,code.
- On clicking the node, there is tab of nde properties.
-Default dashboard.
-IA_function for node styling.
-It supports exporting of query data to JSON and XLS format.
-It provides Java Script to be accessed by any UI MVC Framework like Node JS.
