### ISSUE TITLE
Bug: Query Tab

### ISSUE THREAD

**Issue by ankitvats1** [innovolve-ai/typerefinery#397]
Dirty Form logic not working as expected. (same as #396)

![image](https://user-images.githubusercontent.com/54830888/199174263-482eefbf-2c8c-4d81-b6eb-f1ae9b4b410c.png)

Also, Buttons are not fully visible on the screen.

**Comment by ankitvats1** [comment]
Remove the Query Tab from the top.
![image](https://user-images.githubusercontent.com/54830888/199174671-502ab895-487e-4b77-abd9-596590b5cf03.png)

**Comment by Shivam-apna** [comment]
Covered in #396
