### ISSUE TITLE
Feature: come up with new logo.

### ISSUE THREAD

**Issue by wildone** [innovolve-ai/typerefinery#77]
Current logo is of innovolve, we need one for this app. Something representing graph and analysis.

**Comment by sanjayaapna** [comment]
After discussing this in the regular call the final Logo image would be as shown below:
![MicrosoftTeams-image (21)](https://user-images.githubusercontent.com/96102060/167571148-a358fd2d-6dc3-43d6-8f4d-87d7761fbf51.png)

Blue version of Logo as SVG:
![Type Refinery Logo- Blue](https://user-images.githubusercontent.com/96102060/167571238-543a08c2-b56c-41d0-8544-d7e0917e5d57.svg)

White version of Logo as SVG:
![Type Refinery Logo- White](https://user-images.githubusercontent.com/96102060/167571326-a17d0c68-273d-4294-9a13-4df224baeb8f.svg)

**Comment by sanjayaapna** [comment]
SVG files with Text
![Type Refinery Logo- white (1)](https://user-images.githubusercontent.com/96102060/170202373-eceaf1de-871e-47cb-86b2-4ef49594c473.svg)
![Type Refinery Logo- blue (1)](https://user-images.githubusercontent.com/96102060/170202394-20e1d459-3db2-4357-a425-44749b562e87.svg)
